project:
  type: website
  output-dir: docs

website:
  title: " Mfundo Monchwe"
  favicon: "logo.jpg"
  image: "logo.jpg"
  repo-url: https://github.com/Mfundo-debug/Mfund-debug.github.io
  repo-actions: [edit, issue]
  reader-mode: true
  page-footer: "Copyright Â© 2024, Mfundo Monchwe"
  navbar:
    logo: "logo.jpg"
    background: primary
    search: true
    right:
      - href: index.qmd
        text: Home
        file: index.qmd
      - about.qmd
      - papers.qmd
      - Achievements.qmd
      - projects.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



